/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimesGenRouteImport } from './routes/primes-gen'
import { Route as PrimesRouteImport } from './routes/primes'
import { Route as IndexRouteImport } from './routes/index'

const PrimesGenRoute = PrimesGenRouteImport.update({
  id: '/primes-gen',
  path: '/primes-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimesRoute = PrimesRouteImport.update({
  id: '/primes',
  path: '/primes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/primes': typeof PrimesRoute
  '/primes-gen': typeof PrimesGenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/primes': typeof PrimesRoute
  '/primes-gen': typeof PrimesGenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/primes': typeof PrimesRoute
  '/primes-gen': typeof PrimesGenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/primes' | '/primes-gen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/primes' | '/primes-gen'
  id: '__root__' | '/' | '/primes' | '/primes-gen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrimesRoute: typeof PrimesRoute
  PrimesGenRoute: typeof PrimesGenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primes-gen': {
      id: '/primes-gen'
      path: '/primes-gen'
      fullPath: '/primes-gen'
      preLoaderRoute: typeof PrimesGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primes': {
      id: '/primes'
      path: '/primes'
      fullPath: '/primes'
      preLoaderRoute: typeof PrimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrimesRoute: PrimesRoute,
  PrimesGenRoute: PrimesGenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
